version: 2.1
jobs:
  e2e:
    machine:
      # Choose an explicit machine image so that we get the latest version of
      # docker-compose. Circle's default version won't fail if the target app
      # fails to build.
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Perform end-to-end tests.
          command: |
            cd e2e
            docker-compose up --exit-code-from cypress
      - store_artifacts:
          path: e2e/cypress/videos
      - store_artifacts:
          path: e2e/cypress/screenshots
workflows:
  test:
    jobs:
      - e2e
